name: e2e tests

on:
  push:
    branches:
      - main
      - playwright-tests
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Install Wasp
        run: curl -sSL https://get.wasp-lang.dev/installer.sh | sh -s

      - name: Docker setup
        uses: docker/setup-buildx-action@v1

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('app/package-lock.json') }}

      - name: Install Node.js dependencies
        run: |
          cd app
          npm ci

      - name: Setup Env Vars not in github secrets
        run: |
          cd app
          ls -la
          test -f .env.server && echo ".env.server exists" || echo ".env.server does not exist"
          cp .env.server.example .env.server

      - name: Commit and push if it's not up-to-date
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          cd app
          git add -f .env.server
          git commit -m "Add .env.server file" -a || echo "No changes to commit"
          git push
          
      - name: Set up Playwright
        run: |
          cd app
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd app
          DEBUG=pw:webserver npx playwright test tests/whatever.spec.ts