name: Retag Commit

on:
  push:
    branches:
      # - main
      - playwright-tests
      

jobs:
  retag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
      - name: Delete Old Tag
        run: |
          git tag -d wasp-v0.12-test || true 
          git push origin :refs/tags/wasp-v0.12-test || true

      - name: Add New Tag
        run: |
          git tag wasp-v0.12-test
          git push origin wasp-v0.12-test